---

- name: Install nginx
  hosts: all
  become: true

  tasks:
  - name: Add epel-release repo
    command: yum install epel-release -y && rpm -Uvh http://rpms.famillecollet.com/enterprise/remi-release-7.rpm && rpm -Uvh http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm

  - name: Install php 7
    command: yum --enablerepo=remi-php72 install php -y

  - name: install required modules
    command: yum --enablerepo=remi-php72 search php && yum --enablerepo=remi-php72 install php-mysql php-xml \ php-soap php-xmlrpc php-mbstring php-json php-gd php-mcrypt -y
 
  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Start NGiNX
    service:
      name: nginx
      state: started
 
  - name: Reload NGINX
    command: nginx -s reload

  - name: Allow http/https
    command: firewall-cmd --zone=public --permanent --add-service=http --add-service=https

  - name: Reload firewall
    command: firewall-cmd --reload
 
  - name: Set authorized keys taken from url
    authorized_key:
     user: root
     state: present
     key: "{{ lookup('file', 'id_rsa.pub') }}"
 
  - name: Setup PHP-FPM
    command: yum --enablerepo=remi-php72 install php-fpm -y
  - name: Restart services
    command: systemctl restart nginx.service && systemctl restart php-fpm.service
