---

- name: Install nginx
  hosts: all
  become: true

  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Start NGiNX
    service:
      name: nginx
      state: started

  - name: Allow http/https
    command: firewall-cmd --zone=public --permanent --add-service=http --add-service=https
  - name: Reload firewall
    command: firewall-cmd --reload
 
  - name: Set authorized keys taken from url
    authorized_key:
     user: root
     state: present
     key: "{{ lookup('file', 'id_rsa.pub') }}"
- hosts: all
  roles:
     - ansible-php-fpm
