---

- name: Install nginx
  hosts: all
  become: true

  tasks:
  - name: Add epel-release repo
    command: yum install epel-release -y 
  - name: rpm1
    command: rpm -Uvh --force http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
  - name: rpm2
    command: rpm -Uvh --force http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm

  - name: Install php 7
    command: yum --enablerepo=remi-php72 install php -y

  - name: install required modules
    command: yum --enablerepo=remi-php72 install php-mysql php-xml \ php-soap php-xmlrpc php-mbstring php-json php-gd php-mcrypt -y
 
  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Start NGiNX
    service:
      name: nginx
      state: started
  - name: Default file virtual
    template:
     src: default.conf
     dest: /etc/nginx/conf.d/default.conf
  - name: WWW file
    template:
     src: www.conf
     dest: cat /etc/php-fpm.d/www.conf

  - name: Reload NGINX
    command: nginx -s reload

  - name: Allow http/https
    command: firewall-cmd --zone=public --permanent --add-service=http --add-service=https

  - name: Reload firewall
    command: firewall-cmd --reload
 
  - name: Set authorized keys taken from url
    authorized_key:
     user: root
     state: present
     key: "{{ lookup('file', 'id_rsa.pub') }}"
 
  - name: Setup PHP-FPM
    command: yum --enablerepo=remi-php72 install php-fpm -y

  - name: Restart services
    command: systemctl restart nginx.service
  - name: Restart services 2    
    command: systemctl restart php-fpm.service
