---

- name: Install nginx
  hosts: all
  become: true

  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Insert Index Page
    template:
      src: index.html
      dest: /usr/share/nginx/html/index.html

  - name: Start NGiNX
    service:
      name: nginx
      state: started

  - name: Allow http/https
    command: firewall-cmd --zone=public --permanent --add-service=http --add-service=https
  - name: Reload firewall
    command: firewall-cmd --reload 
  - name: Set authorized keys taken from url
    authorized_key:
     user: charlie
     state: present
     key: https://github.com/SamuelLachance/Tp2Jenkins/blob/master/Public.keys
- hosts: all
  roles:
     - ansible-php-fpm
